# code: language=ansible
---
- name: Install jc task
  ansible.builtin.import_tasks:
    file: dependency/jc.yml
- name: Install osv-scanner task
  ansible.builtin.import_tasks:
    file: dependency/osv-scanner.yml
