# code: language=ansible
---
- name: Install report dependency packages
  ansible.builtin.apt:
    name: "{{ report_dependency_packages | default([]) }}"
- name: Add report group
  ansible.builtin.group:
    name: "{{ report_group }}"
    system: true
- name: Add report user
  ansible.builtin.user:
    name: "{{ report_user }}"
    group: "{{ report_group }}"
    system: true
- name: Create install directory
  ansible.builtin.file:
    path: "{{ report_root }}"
    owner: "{{ report_user }}"
    group: "{{ report_group }}"
    state: directory
    mode: "0755"
