# code: language=ansible
---
# - name: Restart report
#   ansible.builtin.systemd_service:
#     state: restarted
#     name: report
# - name: Reload report
#   ansible.builtin.systemd_service:
#     state: reloaded
#     name: report
