# code: language=ansible
---
- name: Create/update systemd unit file
  ansible.builtin.template:
    src: report.service.j2
    dest: /lib/systemd/system/report.service
    mode: "0644"
  notify: Restart report
- name: Service report is active and enabled on system startup
  ansible.builtin.systemd_service:
    name: report
    state: started
    enabled: true
# - name: Allow report port
#   community.general.ufw:
#     rule: allow
#     port: "{{  report_port }} "
#     from_ip: "{{ report_allow_connect_other_host | default('any') }} "
#   when: report_allow_connect_other_host is defined
